accepted = ["MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "Zlib", "ISC", "CC0-1.0", "Unicode-3.0", "Unicode-DFS-2016", "Unlicense"]
targets = ["x86_64-pc-windows-msvc"]

[windows-collections.clarify]
license = "MIT OR Apache-2.0"
[[windows-collections.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-core.clarify]
license = "MIT OR Apache-2.0"
[[windows-core.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-future.clarify]
license = "MIT OR Apache-2.0"
[[windows-future.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-implement.clarify]
license = "MIT OR Apache-2.0"
[[windows-implement.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-interface.clarify]
license = "MIT OR Apache-2.0"
[[windows-interface.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-link.clarify]
license = "MIT OR Apache-2.0"
[[windows-link.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-numerics.clarify]
license = "MIT OR Apache-2.0"
[[windows-numerics.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-result.clarify]
license = "MIT OR Apache-2.0"
[[windows-result.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-strings.clarify]
license = "MIT OR Apache-2.0"
[[windows-strings.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-threading.clarify]
license = "MIT OR Apache-2.0"
[[windows-threading.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows.clarify]
license = "MIT OR Apache-2.0"
[[windows.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[accesskit.clarify]
license = "MIT OR Apache-2.0"
override-git-commit = "a55d3e1a18bb9ef0e4bccc9083fb13c3e0ad8969"
[[accesskit.clarify.git]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "23f18e03dc49df91622fe2a76176497404e46ced8a715d9d2b67a7446571cca3"

[accesskit_consumer.clarify]
license = "MIT OR Apache-2.0"
override-git-commit = "c88605b96d04431f9c3c792464a0f2f253480e94"
[[accesskit_consumer.clarify.files]]
path = "../../native-rust-notices/accesskit-MIT"
license = "MIT"
checksum = "23f18e03dc49df91622fe2a76176497404e46ced8a715d9d2b67a7446571cca3"

[accesskit_windows.clarify]
license = "MIT OR Apache-2.0"
override-git-commit = "c88605b96d04431f9c3c792464a0f2f253480e94"
[[accesskit_windows.clarify.files]]
path = "../../native-rust-notices/accesskit-MIT"
license = "MIT"
checksum = "23f18e03dc49df91622fe2a76176497404e46ced8a715d9d2b67a7446571cca3"
