accepted = ["MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "Zlib", "ISC", "CC0-1.0", "Unicode-3.0", "Unicode-DFS-2016", "Unlicense"]
targets = ["x86_64-pc-windows-msvc"]

[windows-collections.clarify]
license = "MIT OR Apache-2.0"
[[windows-collections.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-core.clarify]
license = "MIT OR Apache-2.0"
[[windows-core.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-future.clarify]
license = "MIT OR Apache-2.0"
[[windows-future.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-implement.clarify]
license = "MIT OR Apache-2.0"
[[windows-implement.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-interface.clarify]
license = "MIT OR Apache-2.0"
[[windows-interface.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-link.clarify]
license = "MIT OR Apache-2.0"
[[windows-link.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-numerics.clarify]
license = "MIT OR Apache-2.0"
[[windows-numerics.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-result.clarify]
license = "MIT OR Apache-2.0"
[[windows-result.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-strings.clarify]
license = "MIT OR Apache-2.0"
[[windows-strings.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows-threading.clarify]
license = "MIT OR Apache-2.0"
[[windows-threading.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[windows.clarify]
license = "MIT OR Apache-2.0"
[[windows.clarify.files]]
path = "license-mit"
license = "MIT"
checksum = "c2cfccb812fe482101a8f04597dfc5a9991a6b2748266c47ac91b6a5aae15383"

[gpu-descriptor.clarify]
license = "MIT OR Apache-2.0"
override-git-commit = "bb28b4e55b742e0ea3e7a0968e7ee6287ba0e06a"
[[gpu-descriptor.clarify.git]]
path = "license/MIT"
license = "MIT"
checksum = "5226e27d5fbc683db56c52853cdb9d15b69abadb525a60f95c862c2dbd77cdc8"

[gpu-descriptor-types.clarify]
license = "MIT OR Apache-2.0"
override-git-commit = "9f2fb9546591322e7b77ee1e79385e01effd85e4"
[[gpu-descriptor-types.clarify.git]]
path = "license/MIT"
license = "MIT"
checksum = "5226e27d5fbc683db56c52853cdb9d15b69abadb525a60f95c862c2dbd77cdc8"

[profiling.clarify]
license = "MIT OR Apache-2.0"
override-git-commit = "8271551172eb6fa4cba47369aedd93790c623df9"
[[profiling.clarify.git]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "c8167fdeeed46d3f244d3f85c5bf998ce889343691c32be2c61a8bc4b5c08333"

[libm.clarify]
license = "MIT"
[[libm.clarify.files]]
path = "LICENSE.txt"
license = "MIT"
checksum = "3823dda7cf046602f4b4e77ec8e227863dc4736037cc85bb33d9f19febe16bb7"
